version: '3.1'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: sh -c "yarn install && yarn run start"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: sh -c "go run main.go"
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
